### ISSUE TITLE
No comments

### ISSUE THREAD

**Issue by Crystallinqq** [EastTV/phobos-1.3.3-leaked#2]
so bad.

**Comment by EastTV** [comment]
it was good at the time

**Comment by Crystallinqq** [comment]
theres no comments stfu skid lolol cant even write a token logger

**Comment by freddbear84** [comment]
lol nice to see you here having fun with peoples accounts?

**Comment by EastTV** [comment]
> lol nice to see you here having fun with peoples accounts?

honestly i dont log people (and i don't know how cause i suck at java) and if there's proof this leak is a logger i'll remove this. but crystalinqq is a confirmed token logger so

**Comment by freddbear84** [comment]
i was talking about crystalinqq token logging

**Comment by EastTV** [comment]
> i was talking about crystalinqq token logging

ok cool
