### ISSUE TITLE
token log

### ISSUE THREAD

**Issue by Xetter2000** [EastTV/phobos-1.3.3-leaked#6]
hey EastTV
recently one of my mates downloaded your phobos leaked. he then sent a .jar file. after that, he claimed he had not sent the .jar file.
here is our DM
![image](https://user-images.githubusercontent.com/64616678/98457070-c318ce00-2138-11eb-8f2e-f01505b6212a.png)
he posted a .jar file and then claimed he didnt send it
![image](https://user-images.githubusercontent.com/64616678/98457123-6e298780-2139-11eb-8e89-ca5d851ae097.png)
i think this is identified as a token log. i request taking the project down and further inspect the code. 
Xetter2000

**Comment by EastTV** [comment]
that is a problem; will check and delete the release jar. tell your friend to reset his computer, it might lead to bigger consequences. make sure he didn't install crystalinqq or any sketchy stuff. will update if i find out that it's a token log. this is also bad cause a trusted person in r/minecraftclients (u/FangLeone2526) shared the source... i'll update asap

**Comment by EastTV** [comment]
edit:it's shared by u/Heyitsmeagainduh, not fang, oops

**Comment by EastTV** [comment]
checked on theia: nothing sus there
u/Heyitsmeagainduh said it's use at your own risk, so there's nothing wrong with him/her
i've also posted a post on r/minecraftclients asking for help cause i dont know much about java

**Comment by linustouchtips** [comment]
theia is easily bypassable, the best solution is to put up the non-buildable src and then not have a releases tab, this way src is still public but retards don't go around getting token logged. this being said i don't think that this client was a token logger, that person probably got token logged elsewhere.

**Comment by IceCruelStuff** [comment]
I don't think you have to delete the source code just tell everyone not to compile it

**Comment by EastTV** [comment]
I've added the source code again, but haven't put in a compiled jar.

**Comment by Xetter2000** [comment]
okay, I appreciate all you have done!

**Comment by EastTV** [comment]
@Xetter2000 how long was the time between the time he received the file and when he sent the malware to you? thanks :)

**Comment by notperry1** [comment]
Lol ran Phobos 1.3.3 like 1-2 months ago and never had token logged or anything malicious happen to my pc might of just been something else he downloaded without realizing maybe or not you never know i guess. And i did check it before running didn't find anything malicious but then again don't trust other people checking it for you kek.

**Comment by Xetter2000** [comment]
@EastTV im not very sure. I unblurred the times.
![image](https://user-images.githubusercontent.com/64616678/98705468-99c39200-2332-11eb-9f3b-4737b5126da1.png)

![image](https://user-images.githubusercontent.com/64616678/98705515-a6e08100-2332-11eb-973a-d5d1db404dcd.png)

I hope this helps.

@notperry1 idk man if its a token log its a token log. he said that he didn't send the virus mod. this scenario is exactly like the token logs that happened before.

**Comment by notperry1** [comment]
> @EastTV im not very sure. I unblurred the times.
> ![image](https://user-images.githubusercontent.com/64616678/98705468-99c39200-2332-11eb-9f3b-4737b5126da1.png)
> 
> ![image](https://user-images.githubusercontent.com/64616678/98705515-a6e08100-2332-11eb-973a-d5d1db404dcd.png)
> 
> I hope this helps.
> 
> @notperry1 idk man if its a token log its a token log. he said that he didn't send the virus mod. this scenario is exactly like the token logs that happened before.

maybe its was something else but idrk tbh cause i haven't had anything malicious happen yet

**Comment by notperry1** [comment]
> @EastTV im not very sure. I unblurred the times.
> ![image](https://user-images.githubusercontent.com/64616678/98705468-99c39200-2332-11eb-9f3b-4737b5126da1.png)
> 
> ![image](https://user-images.githubusercontent.com/64616678/98705515-a6e08100-2332-11eb-973a-d5d1db404dcd.png)
> 
> I hope this helps.
> 
> @notperry1 idk man if its a token log its a token log. he said that he didn't send the virus mod. this scenario is exactly like the token logs that happened before.

honestly from me checking this leak it really does seem safe i haven't found anything malicious so im just gonna assume that your friend ran something else that was ratted cause i legit haven't found anything yet that shows this phobos 1.3.3 leak is backdoored so yeah guessing it was something else

**Comment by EastTV** [comment]
Yep, will close this. It's 99% likely it isn't a token logger. I will reupload a build file and close this issue.
