### ISSUE TITLE
Src 

### ISSUE THREAD

**Issue by CynicalMuffin** [EastTV/phobos-1.3.3-leaked#8]
Is the source code reviewed since i have been using a phobos 1.3.3 and im not too sure if its clean 
but the client is rly good

**Comment by linustouchtips** [comment]
it has and it has been confirmed as a cord logger, but it has since been removed

**Comment by CynicalMuffin** [comment]
so the build from here is safe?

**Comment by EastTV** [comment]
there is speculation that this leak isn't safe (and i didn't make this so idk), but it's unlikely. if you _really_ want it, dm me on discord or something
i'm not sure how @linustouchtips got the idea that it's a coord log, it's only been speculated (rn) to be a token log (although as i explained, it's unlikely)
